#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DOC_DIR="$ROOT_DIR/doc"
SYSTEM_DIR="$DOC_DIR/system"
DESIGNATION_FILE="$SYSTEM_DIR/designation.txt"

if [[ ! -f "$DESIGNATION_FILE" ]]; then
  echo "missing designation file: $DESIGNATION_FILE"
  exit 1
fi

DESIGNATION="$(tr -d '[:space:]' < "$DESIGNATION_FILE")"
if [[ ! "$DESIGNATION" =~ ^[A-Z]{3}$ ]]; then
  echo "designation must be exactly 3 uppercase letters"
  exit 1
fi

OUTFILE="$DOC_DIR/${DESIGNATION}SYSTEM.md"
TMPFILE="$OUTFILE.tmp"

required_paths=(
  "$SYSTEM_DIR/00_overview/00_identity.md"
  "$SYSTEM_DIR/00_overview/01_purpose_and_scope.md"
  "$SYSTEM_DIR/00_overview/02_architecture_overview.md"
  "$SYSTEM_DIR/10_contract-surface/00_contract_surface.md"
  "$SYSTEM_DIR/20_versioning/00_versioning_and_slice_progression.md"
  "$SYSTEM_DIR/30_dependencies/00_dependencies.md"
  "$SYSTEM_DIR/40_validation/00_validation_and_proof.md"
  "$SYSTEM_DIR/99_appendices/00_glossary_and_paths.md"
)

for path in "${required_paths[@]}"; do
  if [[ ! -f "$path" ]]; then
    echo "missing required source file: $path"
    exit 1
  fi
done

{
  echo "# ${DESIGNATION}SYSTEM"
  echo
  echo "Generated by: doc/system/BUILD.sh"
  echo "Generated on: $(date '+%Y-%m-%d %I:%M:%S %p %Z')"
  echo
  for path in "${required_paths[@]}"; do
    cat "$path"
    echo
  done
} > "$TMPFILE"

mv "$TMPFILE" "$OUTFILE"
echo "built $OUTFILE"
